---
title: "data_visualisation"
author: "Kristine Stoltenberg Addington"
date: "6/17/2021"
output: html_document
---
```{r}
# Load packages
source(here::here("R/package-loading.R"))

# Load the small, tidied dataset from the wrangling session
load(here::here("data/nhanes_small.rda"))

```

# One variable plots 

```{r continuous-variables}
# Create density plot for BMI
ggplot(nhanes_small, aes (x = bmi)) +
    geom_density()

# Create histogram for BMI
ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()
```


```{r descrete-variables}
# Create count barplot for sex
ggplot(nhanes_small, aes(x = sex)) +
    geom_bar()

# Create count barplot for diabetes status
ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()

```


```{r remove-missing-diabetes}
# Remove individuals with missing diabetes status
nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes))

# Save the tidied dataset as an rda file in the data folder
usethis::use_data(nhanes_tidied, overwrite = TRUE)

# Create a new count barplot for diabetes status
ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()

```

# Plotting two variables

```{r two-continous-variables}
#using two continuus variables 
bmi_chol <- ggplot(nhanes_tidied, aes(x = bmi, y = tot_chol))

# Standard scatter plot
bmi_chol +
    geom_point()

# Standard scatter plot, but with hexagons
bmi_chol + 
    geom_hex()

# Runs a smoothing line with confidence interval
bmi_chol + 
    geom_smooth()

# Or combine two geoms, hex plot with smoothing line
bmi_chol + 
    geom_hex() +
    geom_smooth()

```

```{r two-descrete-variables}
# Two categorical/discrete variables
# Note that we can pipe data into ggplot

two_descrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex))

# Stacked
two_descrete +
    geom_bar()

# "dodged" (side-by-side) bar plot
two_descrete +
    geom_bar(position = position_dodge())

```

```{r descrete-continous-variables}

# Using mixed data
two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

# Standard boxplot with outliers
two_mixed + 
    geom_boxplot()

# Show the actual data using a jitter plot
two_mixed +
    geom_jitter()

# Show the distribution with a violin plot
two_mixed + 
    geom_violin()

```

# Excersise to make plots with one or two variables

```{r}
# 1a. Distribution of age
ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()

# 2b. Number of people who are physically active
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()
    
# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, fill = phys_active)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()
```

# Plotting 3 or more variables

```{r using-colour}
# Question: Is systolic blood pressure different in those with or without diabetes in females and males? - example on using one continuous and two descrete variables 
# Plot systolic blood pressure in relation to sex and diabetes status

nhanes_tidied %>% 
    ggplot(aes(x = sex, y = bp_sys_ave, colour = diabetes)) + 
    geom_boxplot()


# Question: How does BMI relate to systolic blood pressure and age? Here, we have three continuous variables
# Plot BMI in relation to systolic blood pressure and age

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) + 
    geom_point()

# Question: How does BMI relate to systolic blood pressure, and what is different between those with and without diabetes?
# two continuous and one descrete variables 
# Plot BMI in relation to systolic blood pressure and diabetes status

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) +
    geom_point()

```

```{r using-facetting}
# For this latter plot, it’s really hard to see what’s different. But there is another way of visualizing a third (or fourth, and fifth) variable: with “faceting!”
# faceting by column - side-by-side

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() +
    facet_grid(cols = vars(diabetes))

# faceting by row - stacked
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave)) + 
    geom_point() +
    facet_grid(rows = vars(diabetes))

# Plot BMI in relation to systolic blood pressure, age, sex and diabetes status - five variables 

nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) + 
    geom_point() +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex))

```

# Exercise for changing colours

```{r}
#exercise-discrete-variables
# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

```

# changing colours 
```{r viridis}
# Barplot to work from, with two discrete variables
base_barplot <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = sex)) +
    geom_bar(position = position_dodge())

#if you want to see it:
base_barplot

#change colors - use different options with letters
base_barplot +
    scale_fill_viridis_d(option = "G")

# Scatterplot to work from, with three continuous variables
base_scatterplot <- nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

#use the option argument to set the palette to "B" and see how the colour changes
base_scatterplot +
    scale_color_viridis_c(option = "B")

```

# 11.9 Titles, axis labels, and themes

# changing plot apperance 

```{r built in themes}
# Create scatterplot to play with themes
base_scatterplot2 <- base_scatterplot +
    facet_grid(rows = vars(diabetes),
               cols = vars(sex)) +
    scale_color_viridis_c()

# View the plot with the default theme
base_scatterplot2

#try different theme
base_scatterplot2 +
    theme_minimal() 

#set the theme for all plots (black and white) 
theme_set(theme_bw())

#change title and axis labels 
base_scatterplot2 + 
    labs(title = "bmi, systolic blodpreassure, and age by diabetes and sex", y = "Systolic Blood Pressure (mmHg)",
         x = "BMI (kg/m2)")


```

# saving the plot 

```{r}
ggsave(here::here("doc/Images/scatterplot.pdf"),
       base_scatterplot2, width = 7, height = 5)
```

